-- Generated by scripts/sync_supabase.py
create table if not exists app_kv (
  key text primary key,
  value jsonb not null default '[]'::jsonb
);

delete from app_kv where key in ('press_users','press_servers','press_settings','press_articles');

insert into app_kv(key, value) values ('press_users', $json$
[
  {
    "username": "joshibot",
    "display_name": "Das_monster23",
    "role": "owner",
    "password_hash": "scrypt:32768:8:1$ETKhLmcX7zSC1ijf$51d28658352fb5cf0ab69f213ad99be188ec3bca81cb825d4134f05bd88c438756eeb9e2266199c4b56ca4fd095af150e90726099706ac2dea5cc7f1953726d7",
    "created_at": "15.02.2026 01:39",
    "server_id": "6797ac6d-3d71-4db2-a79d-1bf2095e9e92"
  },
  {
    "username": "das_monster23",
    "display_name": "Das_monster23",
    "role": "asw",
    "password_hash": "scrypt:32768:8:1$EmhN91bmfDPIMpob$3fc139c95be6ca1209fe93e07e356c89233a38119595eb2696ed9cb403a4428fc89658e6a7a321f9771dcd7facca88f572c39211c62f2990fed21ce25ff6380c",
    "created_at": "15.02.2026 01:40",
    "server_id": "6797ac6d-3d71-4db2-a79d-1bf2095e9e92"
  },
  {
    "username": "joshuaderking23",
    "display_name": "Das_monster23",
    "role": "owner",
    "server_id": "136a5f2d-3c69-491c-b862-03892af45cdb",
    "password_hash": "scrypt:32768:8:1$gh3PecNW8Kn04UjB$77405d76889ec0e0a7f417620e8b54355bba87b40c0e347ca61d0487f7dfc045edc3fdb35d3c021f5beb060a339716e4409a380ec81a04c4355e4f62017e2948",
    "created_at": "15.02.2026 01:53"
  }
]
$json$::jsonb);

insert into app_kv(key, value) values ('press_servers', $json$
[
  {
    "id": "6797ac6d-3d71-4db2-a79d-1bf2095e9e92",
    "name": "Standard Server",
    "server_code": "default",
    "created_at": "15.02.2026 01:49",
    "owner_username": "joshibot"
  },
  {
    "id": "136a5f2d-3c69-491c-b862-03892af45cdb",
    "name": "Berufsfeuerwehr München",
    "server_code": "1469665998226587813",
    "created_at": "15.02.2026 01:53",
    "owner_username": "joshuaderking23"
  }
]
$json$::jsonb);

insert into app_kv(key, value) values ('press_settings', $json$
[
  {
    "server_id": "6797ac6d-3d71-4db2-a79d-1bf2095e9e92",
    "asw_webhook_url_1": "https://discord.com/api/webhooks/1472314093196022043/e7akb9JtbpZwsD1eOuHmLpL_NoaowDLhNiUGc-Dt5Y_C8RLfnKdAh21olfgoWbxtA34j",
    "asw_webhook_url_2": "",
    "webhook_url_1": "https://discord.com/api/webhooks/1472373967405973555/YweZPF4fiE_DbSHWG9PYUfORmGF50IKz88y2E0QS4dhmnPXCO62ah9YF7YcRIyU8vQUc",
    "webhook_url_2": "",
    "menu_background_url": "",
    "role_configs": {
      "owner": {
        "label": "Owner",
        "permissions": [
          "atemschutz_access",
          "presse_access",
          "staff_list_access",
          "create_users",
          "approve_articles"
        ]
      },
      "leitung": {
        "label": "Leitung",
        "permissions": [
          "atemschutz_access",
          "presse_access",
          "staff_list_access",
          "create_users",
          "approve_articles"
        ]
      },
      "mitglied": {
        "label": "Presse Mitglied",
        "permissions": [
          "atemschutz_access",
          "presse_access",
          "staff_list_access"
        ]
      },
      "asw": {
        "label": "Atemschutz",
        "permissions": [
          "atemschutz_access"
        ]
      }
    },
    "updated_at": "15.02.2026 11:27",
    "updated_by": "joshibot"
  },
  {
    "server_id": "136a5f2d-3c69-491c-b862-03892af45cdb",
    "asw_webhook_url_1": "https://discord.com/api/webhooks/1472314093196022043/e7akb9JtbpZwsD1eOuHmLpL_NoaowDLhNiUGc-Dt5Y_C8RLfnKdAh21olfgoWbxtA34j",
    "asw_webhook_url_2": "",
    "webhook_url_1": "https://discord.com/api/webhooks/1472373967405973555/YweZPF4fiE_DbSHWG9PYUfORmGF50IKz88y2E0QS4dhmnPXCO62ah9YF7YcRIyU8vQUc",
    "webhook_url_2": "https://discord.com/api/webhooks/1472373967405973555/YweZPF4fiE_DbSHWG9PYUfORmGF50IKz88y2E0QS4dhmnPXCO62ah9YF7YcRIyU8vQUc",
    "updated_at": "15.02.2026 02:01",
    "updated_by": "joshuaderking23"
  }
]
$json$::jsonb);

insert into app_kv(key, value) values ('press_articles', $json$
[
  {
    "id": "1771117650218",
    "server_id": "136a5f2d-3c69-491c-b862-03892af45cdb",
    "title": "Beförderungen",
    "body": "<:BFMuenchen:1386805907777912913> Beförderungen <:BFMuenchen:1386805907777912913>\r\n\r\nZu jeder guten Dienstbesprechung gehören auch die Beförderungen dazu und in dieser Woche wurde folgende Kameraden und Kameradinnen befördert\r\n\r\nBefördert wurden zur/zum\r\n\r\nBrandmeister/in: e\r\n\r\nOberbrandmeister/in: e\r\n\r\nHauptbrandmeister/in: e\r\n\r\nBrandinspektor/in: e\r\n\r\nBrandinspektor/in mit Zulage: e\r\n\r\nBrandoberinspektoranwärter/in: e\r\n\r\nBrandoberinspektor/in: e\r\n\r\nBrandamtmann/frau: e\r\n\r\nBrandamtsrat/rätin: e\r\n\r\nBrandreferendar/in: e\r\n\r\nBrandrat/rätin: e\r\n\r\nBrandoberrat/rätin: e\r\n\r\nBranddirektor/in: e\r\n\r\nLeitende/r Branddirektor/in: e\r\n\r\n\r\nWir sind stolz auf jeden Einzelnen von Euch und gratulieren  mit einen dreifachen\r\nGUT WEHR",
    "status": "approved",
    "author_role": "owner",
    "author_name": "Das_monster23",
    "created_at": "15.02.2026 02:07",
    "approved_at": "15.02.2026 02:08",
    "approved_by": "Das_monster23"
  },
  {
    "id": "1771118002230",
    "server_id": "136a5f2d-3c69-491c-b862-03892af45cdb",
    "title": "Beförderungen",
    "body": "<:BFMuenchen:1386805907777912913> Beförderungen <:BFMuenchen:1386805907777912913>\r\n\r\nZu jeder guten Dienstbesprechung gehören auch die Beförderungen dazu und in dieser Woche wurde folgende Kameraden und Kameradinnen befördert\r\n\r\nBefördert wurden zur/zum\r\n\r\nBrandmeister/in: Joshua Reimer, s\r\n\r\n\r\nWir sind stolz auf jeden Einzelnen von Euch und gratulieren  mit einen dreifachen\r\nGUT WEHR",
    "status": "approved",
    "author_role": "owner",
    "author_name": "Das_monster23",
    "created_at": "15.02.2026 02:13",
    "approved_at": "15.02.2026 02:13",
    "approved_by": "Das_monster23"
  },
  {
    "id": "1771118046807",
    "server_id": "136a5f2d-3c69-491c-b862-03892af45cdb",
    "title": "1",
    "body": "🔥 1\r\n----------------------------------------------------------------------------------------------\r\n\r\n⏰  | 1 | 1\r\n📟  | 1\r\n🚒  | 1\r\n📍  | 1\r\n\r\n1\r\n\r\nWas ist passiert? 1\r\n\r\nUnsere Maßnahmen vor Ort:\r\n\r\nBrandbekämpfung:\r\n1\r\n\r\nFührung:\r\n1\r\n\r\nAbsicherung:\r\n1\r\n\r\nWichtiger Hinweis für Anwohner:\r\n1\r\n\r\nWir halten euch über die weitere Entwicklung auf dem Laufenden.\r\n\r\nEure Feuerwehr München – Sicher für euch im Einsatz! 🚒💨",
    "status": "approved",
    "author_role": "owner",
    "author_name": "Das_monster23",
    "created_at": "15.02.2026 02:14",
    "approved_at": "15.02.2026 02:14",
    "approved_by": "Das_monster23"
  }
]
$json$::jsonb);
